module.exports = {
  host: "0.0.0.0",
  port: parseInt("3002"),
  origin: "*:*",
  allowedOrigins: [
    "https://d3-events.handbid.dev",
    "https://d3-manager.handbid.dev",
    "http://localhost:4200",
    "http://localhost",
  ],
  allowedServers: ["*"],
  dbOptions: { driver: "dummy", config: [] },
  checkClientOrigin: 0,
  isSecureConnection: 0,
  sessionVarName: "PHPSESSID",
  socketLogFile: "/var/log/yii/node-socket.log",
  checkCertificates: "0",
  keyFile: "/etc/ssl/private/STAR.handbid.dev.key",
  certFile: "/etc/ssl/private/STAR.handbid.dev.bundle.pem",
};
